### ISSUE TITLE
Farmland (aan) test service

### ISSUE THREAD

**Issue by cportele** [geo4web-testbed/ldproxy-design#7]
http://services.interactive-instruments.de/ldproxy/rest/services/aan/

Protected by basic auth until it is ready to be crawled.

**Comment by pvgenuchten** [comment]
Nice work. Some comments
- is it an option to replace 'aan' in the title with the getcapabilities-feature type title
- If there is a schema.org mapping available, use the schema.org property as label in stead of wfs property (for discussion)
- Maybe you can use the layout from the catalogue so the proxied Csw and wfs results all look the same, the detail page includes a leaflet map, so you can plot the geometry on a map (http://opendatacat.net/geonetwork-geo4web/doc/dataset/1BE12300-3CD3-27D3-2CA9-3C05419AE1EB)
- Would be good to provide links back to the proxied Csw response for that dataset

**Comment by pvgenuchten** [comment]
@cportele, so in this case you use 'aan' to reference a certain wfs-endpoint, what would be the scenario if i want to query a wfs which is not known to the proxy yet?
-  like a proxy, use http://services.interactive-instruments.de/ldproxy/rest/services?url=http://new/wfs
- like an api, check if url is available, if not register a new url, as response recieve an identifier, use identifier in proxy-url 
- use the catalogue, in stead of 'aan', use a uuid of a service metadata record, query the catalogue with that uuid and retrieve wfs-url from that.

Advantage of last is that the proxy may not need any storage capabilities, however it will probably have storage capabilities anyway, since you have to store the mapping-configuration from gml to schema.org somewhere. Is it possible to use a wfs if a mapping-configuration is not yet available?

**Comment by azahnen** [comment]
@pvgenuchten: From ldproxy perspective, it looks like this:
- You have to explicitely create a proxy service, providing an id (which we set to 'aan' here) and the WFS URL.
- A default configuration including the mapping is then automatically created. This might be sufficient for many cases, but e.g. for the bag service you have to manually configure the mapping for address.
- Proxy services can be created via REST API.
- In theory there can be multiple proxy services for the same WFS, but in this use case we should avoid that.
- I could implement a REST endpoint that returns the proxy service URL given a WFS URL. This might as well create a proxy service if none exists yet for the WFS URL.
- At least the endpoint for creating a service is secured. That means if geonetwork wants to use that, it either has to authenticate against ldproxy, or we need to install them on the same server and allow local access.

**Comment by pvgenuchten** [comment]
@azahnen, let me know as soon as you have that rest endpoint available, i will then look how to use that

something like ldproxy/service?url=http://wfs-server

I can understand you'd want to add security to the create-service operation, from our side no problem (should this endpoint then run over https?)

Would it be possible to send some config params via that rest endpoint, for example a mapping file in some format, which you then use in setting up the endpoint? In that case you may need also a service-update operation?

Also would be good to have an api-call providing a list of available services and their corresponding wfs-endpoint, so I can cache that on my side.

**Comment by azahnen** [comment]
@pvgenuchten, you can now get the proxy service by wfs url:

www.ldproxy.net/?wfsUrl=http://geodata.nationaalgeoregister.nl/inspireadressen/wfs 
will redirect to the proxy service.
The urls are normlized by removing known parameters like SERVICE, VERSION, etc.

**Comment by cportele** [comment]
The testbed work on the Farmland proxy is now complete
